apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-configmap"
  namespace: "{{ .Values.namespace }}"
data:
  index.html: |
    <!doctype html>
    <html>
      <head><title>hello aranya</title></head>
      <body><h1>hello aranya</h1></body>
    </html>
